#!/usr/bin/perl -w
use strict;
use warnings;
use BitQC;

######################################################################################
# INITIALISE BITQC MODULE
######################################################################################

# Make BitQC object
# settings will come from environment variables
my $BitQC = new BitQC();

# Load bitqc configuration from the given database
$BitQC->load(
	'script_args' => {
		'inputbam' 		   	=> { type => 'string'},
		'region'           	=> { type => 'string'},
		'outputfilename'   	=> { type => 'string'},
		'target_intervals' 	=> { type => 'string'},
	}
);

######################################################################################
# COMMANDS AND VARIABLES
######################################################################################

my $BAM             = $BitQC->getRunConfig('inputbam');
my $REGION          = $BitQC->getRunConfig('region');
my $TARGET_INTERVAL = $BitQC->getRunConfig('target_intervals');
my $REGIONBAM       = $BitQC->getRunConfig('outputfilename');
my $REMOVE 			= $BitQC->getRunConfig('remove');

#Get command
my $GATK_COMMAND = $BitQC->getCommand('gatk');

# genome index
my $GATK_INDEX = $BitQC->getGenomeIndex('gatk');

######################################################################################
# START GATK RECALIBRATION OF FASTQ FILE
######################################################################################

$BitQC->run_and_log(
	message =>
"Determining (small) suspicious intervals which are likely in need of realignment.",
	command => "$GATK_COMMAND "
	  . "-I $BAM "
	  . "-R $GATK_INDEX "
	  . "-L $REGION "
	  . "-T RealignerTargetCreator "
	  . "-o $TARGET_INTERVAL "
);

$BitQC->run_and_log(
	message => "Running the realigner over the intervals",
	command => "$GATK_COMMAND "
	  . "-I $BAM "
	  . "-R $GATK_INDEX "
	  . "-T IndelRealigner "
	  . "-L $REGION "
	  . "-targetIntervals $TARGET_INTERVAL "
	  . "-o $REGIONBAM "
	  . "--consensusDeterminationModel USE_READS "
	  . "-rf NotPrimaryAlignment " # do not take non primary allignments into consideration for this
);

######################################################################################
# FINISH SCRIPT
######################################################################################

if ($REMOVE) {
	unlink($TARGET_INTERVAL);

	# remove the autogenerated index file for the realigned bam
	$REGIONBAM =~ s/bam$/bai/;
	unlink($REGIONBAM);

	$BitQC->log_message( message =>
		  "Removed indel realignement interval list for $REGION of $BAM" );
}

# finish logging
$BitQC->finish_log(
	message =>
"Job completed: GATK local realignment around indels of the region $REGION for bam file $BAM"
);
